# backend/core package
from backend.core.invalidation_engine import InvalidationEngine, evaluate_version_delta
from backend.core.dependency_graph import (
    ClearanceDependencyGraph,
    DependencyGraph,
    NodeType,
    DependencyKind,
    DependencyNode,
    DependencyEdge,
    InvalidationNotice,
    ClearanceGraphError,
    CycleDetectedError,
    NodeNotFoundError,
)
from backend.core.semantic_delta import (
    SemanticLineageTracker,
    SemanticDeltaEngine,
    DeltaAnalysisResult,
    LineagePair,
    LineageStatus,
    ModelContainmentViolation,
    repair_json_output,
)
from backend.core.evidence_reconciler import EvidenceReconciler
from backend.core.revalidation_planner import (
    RevalidationPlanner,
    ResearchPlanner,
    ReconciliationEngine,
    EvidenceStanceCategorizer,
    PlannedRevalidationRequest,
    RevalidationSearchRequest,
    RevalidationPlan,
    EvidenceReconciliationResult,
)
from backend.core.counsel_checkpoint import (
    CounselCheckpointManager,
    CounselCheckpointEngine,
    CounselCheckpointService,
    counsel_checkpoint_manager,
)
from backend.core.security import (
    redact_secrets,
    mask_credential,
    get_masked_preview,
    SecretRedactingFilter,
    generate_correlation_id,
    get_correlation_id,
    StructuredJsonFormatter,
    CorrelationLoggingMiddleware,
    PayloadSizeLimitMiddleware,
    IdempotencyRecord,
    IdempotencyKeyManager,
    IdempotencyMiddleware,
    idempotency_key_manager,
    CounselAuthContext,
    verify_counsel_token,
    is_strict_auth_enabled,
    VALID_COUNSEL_REGISTRY,
    VALID_DEMO_COUNSEL_TOKENS,
    REDACTED_API_KEY,
    MAX_PAYLOAD_SIZE_BYTES,
)
from backend.core.lifecycle import (
    InvalidStateTransitionError,
    LifecycleAuditEvent,
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    coerce_run_status,
    is_terminal_state,
    get_allowed_transitions,
    can_transition,
    validate_transition,
    transition_run,
    RunLifecycleManager,
)
from backend.core.rbac import (
    LienmarkRole,
    LienmarkPermission,
    RBACContext,
    RBACAccessDeniedException,
    RequireRole,
    RequirePermission,
    require_role,
    require_permission,
    extract_rbac_context,
    get_rbac_context,
    normalize_role_name,
)
from backend.core.projector import (
    StateProjector,
    ProductionStateProjection,
    AuditEvent,
    ProjectorError,
    InvalidEventError,
    compute_state_digest,
)
from backend.core.conflict_types import (
    ArbitrationResult,
    ClaimStatusAssertion,
    ConflictStance,
    DualLayerConflictInfo,
    EvidenceFinding,
    RightsLayer,
    SourceAuthorityTier,
    StancePairEvaluation,
)
from backend.core.conflict_heuristics import ConflictHeuristics
from backend.core.conflict_arbiter import (
    CorroborationEngine,
    ConflictArbiter,
    arbitrate_claim_conflicts,
)
from backend.core.statutory_rules import (
    eval_public_domain,
    eval_de_minimis,
    eval_fair_use_scorecard,
)
from backend.core.statutory_types import (
    StatutoryEra,
    FairUseOutcome,
    FocalProminence,
    PublicDomainEvaluation,
    DeMinimisEvaluation,
    FairUseFactors,
    FairUseEvaluation,
    StatutoryRuleError,
    InvalidPublicationYearError,
    InvalidDurationError,
    InvalidProminenceError,
    InvalidFactorScoreError,
)
from backend.core.policy_types import (
    LicensingScope,
    TerritoryScope,
    StudioProfileType,
    StudioPolicyConfig,
    ProductionPolicyOverride,
    PolicyViolation,
    PolicyEvaluationResult,
    RuleEvaluationStatus,
    PolicyActionRequirement,
    PolicyAction,
    CLARIFICATION,
    COUNSEL_REVIEW,
    RuleEvaluationItem,
    compute_policy_digest,
)
from backend.core.policy_rules import (
    get_preset_profile_policy,
    resolve_effective_policy,
    evaluate_claim_against_policy,
    RULE_THEATRICAL_SYNC_PERPETUAL,
    RULE_TRADEMARK_FAIR_USE,
    RULE_TERRITORY_SCOPE,
    RULE_PROMOTIONAL_TRAILER_SECOND_REVIEW,
    RULE_GRANT_VERIFICATION,
)
from backend.core.policy_engine import StudioPolicyEngine, get_policy_engine
from backend.core.decision_package_types import (
    DualReviewStatus,
    PackageApprovalRecord,
    DecisionPackage,
)
from backend.core.decision_package import (
    compute_package_canonical_digest,
    create_decision_package,
    derive_superseded_package,
    is_material_package_difference,
    apply_package_approval,
    reject_package,
    invalidate_package,
)

from backend.core.conflict_checker import (
    ConflictCheckResult,
    check_counsel_conflict,
    register_counsel_conflict,
    clear_conflict_registry,
    get_declared_conflicts,
)
from backend.core.dual_review import (
    DualReviewCoordinator,
    get_dual_review_coordinator,
    is_material_package_change,
)
from backend.core.policy_outbox_types import (
    CascadeAction,
    CascadeTargetFilter,
    ClaimCascadeResult,
    DispatchExecutionReport,
    DispatchIntentStatus,
    PolicyDiffSummary,
)
from backend.core.policy_outbox import (
    PolicyOutboxDispatcher,
    get_policy_outbox_dispatcher,
)

__all__ = [
    "ConflictCheckResult", "check_counsel_conflict", "register_counsel_conflict",
    "clear_conflict_registry", "get_declared_conflicts", "DualReviewCoordinator",
    "get_dual_review_coordinator", "is_material_package_change",
    "CascadeAction", "CascadeTargetFilter", "ClaimCascadeResult",
    "DispatchExecutionReport", "DispatchIntentStatus", "PolicyDiffSummary",
    "PolicyOutboxDispatcher", "get_policy_outbox_dispatcher",
    "DualReviewStatus", "PackageApprovalRecord", "DecisionPackage",
    "compute_package_canonical_digest", "create_decision_package",
    "derive_superseded_package", "is_material_package_difference",
    "apply_package_approval", "reject_package", "invalidate_package",
    "InvalidationEngine", "evaluate_version_delta", "ClearanceDependencyGraph", "DependencyGraph",
    "NodeType", "DependencyKind", "DependencyNode", "DependencyEdge",
    "InvalidationNotice", "ClearanceGraphError", "CycleDetectedError", "NodeNotFoundError",
    "SemanticLineageTracker", "SemanticDeltaEngine", "DeltaAnalysisResult",
    "LineagePair", "LineageStatus", "ModelContainmentViolation", "repair_json_output",
    "EvidenceReconciler", "ReconciliationEngine", "EvidenceStanceCategorizer",
    "RevalidationPlanner", "ResearchPlanner", "PlannedRevalidationRequest",
    "RevalidationSearchRequest", "RevalidationPlan", "EvidenceReconciliationResult",
    "CounselCheckpointManager", "CounselCheckpointEngine", "CounselCheckpointService",
    "counsel_checkpoint_manager", "redact_secrets", "mask_credential", "get_masked_preview",
    "SecretRedactingFilter", "generate_correlation_id", "get_correlation_id",
    "StructuredJsonFormatter", "CorrelationLoggingMiddleware", "PayloadSizeLimitMiddleware",
    "IdempotencyRecord", "IdempotencyKeyManager", "IdempotencyMiddleware",
    "idempotency_key_manager", "CounselAuthContext", "verify_counsel_token",
    "is_strict_auth_enabled", "VALID_COUNSEL_REGISTRY", "VALID_DEMO_COUNSEL_TOKENS",
    "REDACTED_API_KEY", "MAX_PAYLOAD_SIZE_BYTES", "InvalidStateTransitionError",
    "LifecycleAuditEvent", "ALLOWED_TRANSITIONS", "TERMINAL_STATES", "coerce_run_status",
    "is_terminal_state", "get_allowed_transitions", "can_transition",
    "validate_transition", "transition_run", "RunLifecycleManager",
    "LienmarkRole", "LienmarkPermission", "RBACContext", "RBACAccessDeniedException",
    "RequireRole", "RequirePermission", "require_role", "require_permission",
    "extract_rbac_context", "get_rbac_context", "normalize_role_name",
    "StateProjector", "ProductionStateProjection", "AuditEvent", "ProjectorError",
    "InvalidEventError", "compute_state_digest", "ArbitrationResult",
    "ClaimStatusAssertion", "ConflictStance", "DualLayerConflictInfo",
    "EvidenceFinding", "RightsLayer", "SourceAuthorityTier", "StancePairEvaluation",
    "ConflictHeuristics", "CorroborationEngine", "ConflictArbiter",
    "arbitrate_claim_conflicts", "eval_public_domain", "eval_de_minimis",
    "eval_fair_use_scorecard", "StatutoryEra", "FairUseOutcome", "FocalProminence",
    "PublicDomainEvaluation", "DeMinimisEvaluation", "FairUseFactors",
    "FairUseEvaluation", "StatutoryRuleError", "InvalidPublicationYearError",
    "InvalidDurationError", "InvalidProminenceError", "InvalidFactorScoreError",
    "LicensingScope", "TerritoryScope", "StudioProfileType", "StudioPolicyConfig",
    "ProductionPolicyOverride", "PolicyViolation", "PolicyEvaluationResult",
    "RuleEvaluationStatus", "PolicyActionRequirement", "PolicyAction",
    "CLARIFICATION", "COUNSEL_REVIEW", "RuleEvaluationItem", "compute_policy_digest",
    "RULE_THEATRICAL_SYNC_PERPETUAL", "RULE_TRADEMARK_FAIR_USE", "RULE_TERRITORY_SCOPE",
    "RULE_PROMOTIONAL_TRAILER_SECOND_REVIEW", "RULE_GRANT_VERIFICATION",
    "get_preset_profile_policy", "resolve_effective_policy", "evaluate_claim_against_policy",
    "StudioPolicyEngine", "get_policy_engine",
]
