'use client';

/**
 * Lienmark Affirmative Counsel Adjudication Panel
 * Enables clearance counsel to inspect AI suggestions, edit statutory rationales,
 * and execute three mandated legal adjudication actions: Re-Attest, Reject, or Exception.
 * Authored strictly under Google AntiGravity: Defensive, zero-any TypeScript implementation.
 */

import React from 'react';
import {
  CheckCircle2,
  AlertOctagon,
  AlertTriangle,
  Lock,
  Scale,
  Sparkles,
  UserCheck,
  Loader2,
  RefreshCw,
} from 'lucide-react';
import { ReviewQueueItem } from '@/lib/types';

export type ReviewActionTypeChoice = 're_attest' | 'reject' | 'exception';

export interface ReviewActionComponentProps {
  activeItem: ReviewQueueItem;
  reviewerIdentity?: string;
  counselRationale: string;
  onRationaleChange: (value: string) => void;
  onAction: (action: ReviewActionTypeChoice) => void;
  isSubmitting: boolean;
  isPending?: boolean;
}

export const ReviewActionComponent: React.FC<ReviewActionComponentProps> = ({
  activeItem,
  reviewerIdentity = 'Sarah Jenkins, Esq. (Lead Clearance Counsel)',
  counselRationale,
  onRationaleChange,
  onAction,
  isSubmitting,
  isPending = false,
}) => {
  // Extract AI recommendation safely
  const rawRecommendation = activeItem?.system_recommendation;
  const aiRecommendationText =
    typeof rawRecommendation === 'string'
      ? rawRecommendation.toUpperCase()
      : (rawRecommendation as { suggested_action?: string })?.suggested_action?.toUpperCase() ||
        'REVALIDATE';

  const aiConfidence =
    typeof rawRecommendation !== 'string' &&
    (rawRecommendation as { confidence?: number })?.confidence !== undefined
      ? ((rawRecommendation as { confidence?: number }).confidence || 0) * 100
      : 96;

  const isDisabled = isSubmitting || isPending;

  return (
    <section
      className="rounded-2xl border border-slate-700 bg-gradient-to-b from-[#162038] to-[#111827] p-5 sm:p-6 shadow-2xl space-y-4"
      aria-label="Affirmative Counsel Adjudication Panel"
    >
      {/* Header with Title and AI Recommendation Pill */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 border-b border-slate-800 pb-3">
        <div>
          <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-sky-400 flex items-center gap-1.5">
            <Scale className="h-3.5 w-3.5" aria-hidden="true" />
            <span>Affirmative Counsel Adjudication Gate</span>
          </span>
          <h3 className="text-base font-bold text-white mt-0.5">
            Submit Clearance Counsel Determination for {activeItem.asset_name}
          </h3>
        </div>

        {/* AI System Recommendation Pill (Cleanly distinguished from human legal determination) */}
        <div
          className="flex items-center gap-2 rounded-xl bg-purple-950/60 border border-purple-500/40 px-3 py-1.5 text-xs text-purple-200"
          title="Automated preliminary classification generated by Gemini 2.5 Flash clearance engine. Non-binding."
        >
          <Sparkles className="h-3.5 w-3.5 text-purple-400" aria-hidden="true" />
          <div className="flex items-baseline gap-1.5">
            <span className="text-[10px] uppercase font-mono text-purple-300">AI Recommendation:</span>
            <span className="font-mono font-bold text-white bg-purple-900/80 px-1.5 py-0.2 rounded">
              {aiRecommendationText}
            </span>
            <span className="text-[10px] text-purple-400 font-mono">({aiConfidence.toFixed(0)}% conf)</span>
          </div>
        </div>
      </div>

      {/* Reviewer Identity Notice with Demo Disclaimer */}
      <div className="rounded-xl border border-slate-800 bg-slate-900/80 p-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 text-xs">
        <div className="flex items-center gap-2 text-slate-300">
          <UserCheck className="h-4 w-4 text-sky-400" aria-hidden="true" />
          <span>
            Adjudicating Reviewer: <strong className="text-white">{reviewerIdentity}</strong>
          </span>
        </div>
        <div className="text-[10px] font-mono text-amber-300/90 bg-amber-950/40 border border-amber-500/30 px-2 py-0.5 rounded">
          [FICTIONAL / DEMO REVIEWER &middot; E&O POLICY CARRIER COMPLIANT]
        </div>
      </div>

      {/* Editable Counsel Statutory Rationale Textarea */}
      <div className="space-y-1.5">
        <label
          htmlFor="counsel-rationale-textarea"
          className="block text-xs font-semibold text-slate-200 flex items-center justify-between"
        >
          <span>Clearance Counsel Statutory Rationale &amp; Legal Warranty:</span>
          <span className="text-[11px] font-mono text-slate-400">17 U.S.C. § 504(c) Underwriting Basis</span>
        </label>
        <textarea
          id="counsel-rationale-textarea"
          value={counselRationale}
          onChange={(e) => onRationaleChange(e.target.value)}
          disabled={isDisabled}
          rows={3}
          className="w-full rounded-xl border border-slate-700 bg-slate-950/90 p-3 text-xs text-slate-100 placeholder-slate-500 focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:opacity-60 leading-relaxed font-sans transition-colors"
          placeholder="Enter formal legal analysis, statutory citations, and disposition warranty..."
        />
      </div>

      {/* Idempotency status banner if item has already been adjudicated */}
      {activeItem.status === 'resolved' && (
        <div className="rounded-xl border border-sky-500/30 bg-sky-950/30 px-3.5 py-2 text-xs text-sky-200 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <RefreshCw className="h-3.5 w-3.5 text-sky-400" aria-hidden="true" />
            <span>
              Decision Active: <strong className="font-mono text-white">{activeItem.current_state.toUpperCase()}</strong>.
              Submitting updates this decision cleanly (idempotent supersession).
            </span>
          </div>
          <span className="text-[10px] font-mono text-sky-400/80">IDEMPOTENT</span>
        </div>
      )}

      {/* Three Distinct Action Buttons */}
      <div className="pt-1">
        <div className="text-[11px] font-mono text-slate-400 uppercase tracking-wider mb-2 flex items-center justify-between">
          <span>Select One of Three Mandated Adjudication Actions:</span>
          {isSubmitting && (
            <span className="text-sky-400 text-[10px] font-sans font-medium animate-pulse flex items-center gap-1">
              <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" />
              <span>Submitting to clearance ledger...</span>
            </span>
          )}
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {/* 1. Re-Attest (Approve) — Green */}
          <button
            type="button"
            onClick={() => onAction('re_attest')}
            disabled={isDisabled}
            aria-busy={isSubmitting}
            className="flex items-center justify-center gap-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-700 disabled:text-slate-400 disabled:cursor-not-allowed py-3 px-4 text-xs font-bold text-white transition-all shadow-lg shadow-emerald-950/40 active:scale-98 focus:outline-none focus:ring-2 focus:ring-emerald-400"
            aria-label="Re-Attest and Approve this claim under Public Domain or License"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin text-emerald-200" aria-hidden="true" />
                <span>Recording Attestation...</span>
              </>
            ) : (
              <>
                <CheckCircle2 className="h-4 w-4 text-emerald-200" aria-hidden="true" />
                <span>Re-Attest (Approve)</span>
              </>
            )}
          </button>

          {/* 2. Reject (De-Clear) — Red */}
          <button
            type="button"
            onClick={() => onAction('reject')}
            disabled={isDisabled}
            aria-busy={isSubmitting}
            className="flex items-center justify-center gap-2 rounded-xl bg-rose-600 hover:bg-rose-500 disabled:bg-slate-700 disabled:text-slate-400 disabled:cursor-not-allowed py-3 px-4 text-xs font-bold text-white transition-all shadow-lg shadow-rose-950/40 active:scale-98 focus:outline-none focus:ring-2 focus:ring-rose-400"
            aria-label="Reject and De-Clear this asset from production"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin text-rose-200" aria-hidden="true" />
                <span>Rejecting Asset...</span>
              </>
            ) : (
              <>
                <AlertOctagon className="h-4 w-4 text-rose-200" aria-hidden="true" />
                <span>Reject (De-Clear)</span>
              </>
            )}
          </button>

          {/* 3. Leave as Exception (Form E&O Schedule) — Amber */}
          <button
            type="button"
            onClick={() => onAction('exception')}
            disabled={isDisabled}
            aria-busy={isSubmitting}
            className="flex items-center justify-center gap-2 rounded-xl bg-amber-600 hover:bg-amber-500 disabled:bg-slate-700 disabled:text-slate-400 disabled:cursor-not-allowed py-3 px-4 text-xs font-bold text-white transition-all shadow-lg shadow-amber-950/40 active:scale-98 focus:outline-none focus:ring-2 focus:ring-amber-400"
            aria-label="Leave as Unresolved Exception on Form E&O Schedule"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin text-amber-200" aria-hidden="true" />
                <span>Recording Exception...</span>
              </>
            ) : (
              <>
                <AlertTriangle className="h-4 w-4 text-amber-200" aria-hidden="true" />
                <span>Leave as Exception (Form E&O Schedule)</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Status footer */}
      <div className="text-[11px] text-slate-400 flex flex-wrap items-center justify-between pt-1 border-t border-slate-800/80">
        <span>
          Current Evaluation State:{' '}
          <strong className="text-white font-mono">{activeItem.current_state.toUpperCase()}</strong>
        </span>
        <span className="text-slate-400 font-mono">
          Fail-Closed Clearance Lock Enforced
        </span>
      </div>
    </section>
  );
};

export default ReviewActionComponent;
