/**
 * Server-Side Rendered (SSR) Form E&O-2026 Exceptions Schedule
 * Next.js 15 App Router Server Component
 * Generates statutory, print-ready clearance warranty schedule for motion picture underwriters.
 * Authored strictly under Google AntiGravity: Defensive, zero-any TypeScript implementations.
 */

import React from 'react';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import {
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  AlertOctagon,
  CheckCircle2,
  FileText,
  ExternalLink,
  Lock,
  Scale,
  Building2,
  Calendar,
  Hash,
} from 'lucide-react';

import { apiClient } from '@/lib/api_client';
import { DecisionState, ExceptionsSchedule, ExceptionsScheduleItem } from '@/lib/types';
import { getGoldenExceptionsSchedule } from '@/lib/fixtures_data';
import { PrintButton } from './PrintButton';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ production_id: string }>;
}): Promise<Metadata> {
  const { production_id } = await params;
  return {
    title: `Form E&O-2026 Schedule — ${production_id} | Lienmark`,
    description: `Statutory E&O clearance exceptions schedule and certified carried-forward ledger for production ${production_id}.`,
  };
}

export default async function ReportPage({
  params,
}: {
  params: Promise<{ production_id: string }>;
}) {
  const { production_id } = await params;

  let schedule: ExceptionsSchedule;
  try {
    schedule = await apiClient.getExceptionsSchedule();
  } catch (err: unknown) {
    console.warn('[ReportPage] Fallback to golden exceptions schedule:', err);
    schedule = getGoldenExceptionsSchedule();
  }

  // Consume the authentic recorded schedule items directly (zero client synthesis)
  const items: ExceptionsScheduleItem[] = schedule.items;

  const carriedItems = items.filter((it) => it.v8_evaluation_state === DecisionState.CARRIED_FORWARD);
  const reattestedItems = items.filter((it) => it.v8_evaluation_state === DecisionState.RE_ATTESTED);
  const exceptionItems = items.filter(
    (it) => it.v8_evaluation_state === DecisionState.EXCEPTION || it.v8_evaluation_state === DecisionState.STALE
  );

  const formattedDate = new Date().toLocaleDateString('en-US', {
    timeZone: 'UTC',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8 text-slate-100">
      {/* Top Client Print and Download Controls */}
      <div className="no-print print:hidden">
        <PrintButton
          scheduleId={schedule.schedule_id || 'sched_proj_blockbuster_cinema_v8'}
          scheduleData={schedule}
        />
      </div>

      {/* Main Document Body (Print-optimized container) */}
      <div className="print-document rounded-2xl border border-slate-800 bg-[#0f172a] p-6 sm:p-10 shadow-2xl space-y-8">
        {/* PROMINENT STATUTORY UNDERWRITING DISCLAIMER BANNER (HEADER) */}
        <div className="rounded-xl border border-rose-600/50 bg-rose-950/30 p-4 text-xs text-rose-200 leading-relaxed font-sans shadow-inner">
          <strong className="font-bold text-rose-300">LEGAL &amp; UNDERWRITING DISCLAIMER:</strong> THIS ARTIFACT IS A VERSION-BOUND SCHEDULE OF UNRESOLVED CLEARANCE EXCEPTIONS FOR DEMONSTRATION AND INFORMATIONAL PURPOSES ONLY. NO ARTIFACT GENERATED BY LIENMARK CONSTITUTES OR CLAIMS FORMAL UNDERWRITING APPROVAL, POLICY BINDING, INSURANCE COVERAGE, LEGAL OPINION, OR LEGAL CERTAINTY. COVERAGE IS SUBJECT EXCLUSIVELY TO A SEPARATELY EXECUTED POLICY BINDER WITH AN ADMITTED OR SURPLUS LINES CARRIER.
        </div>

        {/* Document Header */}
        <div className="border-b-2 border-slate-700 pb-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 text-xs font-mono font-bold uppercase tracking-widest text-sky-400">
                <ShieldCheck className="h-4 w-4" />
                Lienmark Clearance Change Control System
              </div>
              <h1 className="mt-1 text-2xl sm:text-3xl font-serif font-bold text-white tracking-tight">
                FORM E&amp;O-2026 UNDERWRITER EXCEPTIONS SCHEDULE
              </h1>
              <p className="text-xs text-slate-400 mt-0.5">
                Statutory Motion Picture &amp; Television Clearance Warranty &middot; Standard Form E&amp;O-2026.1
              </p>
            </div>

            <div className="text-right font-mono text-xs text-slate-400">
              <div className="font-bold text-slate-200">SCHEDULE REF:</div>
              <div className="text-sky-300 font-semibold">
                {schedule.schedule_id || 'SCHED-2026-BB-0941'}
              </div>
              <div className="text-[11px] text-slate-500 mt-1">
                POLICY: E&amp;O-2026.1-DEVPOST
              </div>
            </div>
          </div>

          {/* Underwriting Meta Grid */}
          <div className="mt-6 grid grid-cols-2 sm:grid-cols-4 gap-4 rounded-xl border border-slate-800 bg-slate-900/80 p-4 text-xs">
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-500">
                Insured Production
              </span>
              <span className="font-semibold text-slate-200">
                Shadows Over Broadway
              </span>
              <span className="block text-[11px] text-slate-400">Feature Film</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-500">
                Policyholder Entity
              </span>
              <span className="font-semibold text-slate-200">
                Blockbuster Cinema LLC
              </span>
              <span className="block text-[11px] text-slate-400">DE Entity #749210</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-500">
                E&amp;O Lead Underwriter
              </span>
              <span className="font-semibold text-slate-200">
                Lloyd&apos;s Specialty Syndicate 1888
              </span>
              <span className="block text-[11px] text-slate-400">Entertainment Risk Dept</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-500">
                Attestation Date
              </span>
              <span className="font-semibold text-slate-200">
                {formattedDate}
              </span>
              <span className="block text-[11px] text-slate-400">UTC Certified</span>
            </div>
          </div>

          {/* Version Binding Lineage Strip */}
          <div className="mt-3 flex flex-wrap items-center justify-between rounded-lg border border-slate-800 bg-slate-950/60 px-3.5 py-2 text-[11px] text-slate-400 font-mono">
            <div>
              <span className="text-slate-500">Locked Base Cut:</span>{' '}
              <strong className="text-slate-300">Version 7</strong> (Hash:{' '}
              <span className="text-slate-400">a1b2c3d4e5f60718</span>)
            </div>
            <div className="text-slate-500">&rarr;</div>
            <div>
              <span className="text-slate-500">Revised Cut:</span>{' '}
              <strong className="text-slate-300">Version 8</strong> (Hash:{' '}
              <span className="text-slate-400">f9e8d7c6b5a43210</span>)
            </div>
            <div>
              <span className="text-slate-500">Invalidation Protocol:</span>{' '}
              <span className="text-emerald-400 font-semibold">Selective Deterministic Parity</span>
            </div>
          </div>
        </div>

        {/* Executive Summary & Disposition Invariant */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
              <Scale className="h-4 w-4 text-sky-400" />
              Summary of Clearance Disposition &amp; Invariant Balance
            </h2>
            <span className="text-xs font-mono text-emerald-400 font-semibold">
              Invariant Verified: 10 + 1 + 1 = 12
            </span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="rounded-lg border border-slate-800 bg-slate-900/60 p-3 text-center">
              <div className="text-[10px] uppercase font-bold text-slate-400">
                Total Claims
              </div>
              <div className="text-2xl font-bold text-white mt-0.5">12</div>
              <div className="text-[10px] text-slate-500">100% Ingested</div>
            </div>

            <div className="rounded-lg border border-emerald-800/40 bg-emerald-950/20 p-3 text-center">
              <div className="text-[10px] uppercase font-bold text-emerald-400">
                Carried Forward
              </div>
              <div className="text-2xl font-bold text-emerald-400 mt-0.5">10</div>
              <div className="text-[10px] text-emerald-300/80">$0.00 Re-Review Cost</div>
            </div>

            <div className="rounded-lg border border-sky-800/40 bg-sky-950/20 p-3 text-center">
              <div className="text-[10px] uppercase font-bold text-sky-400">
                Re-Attested
              </div>
              <div className="text-2xl font-bold text-sky-400 mt-0.5">1</div>
              <div className="text-[10px] text-sky-300/80">Public Domain (LOC)</div>
            </div>

            <div className="rounded-lg border border-rose-800/40 bg-rose-950/20 p-3 text-center">
              <div className="text-[10px] uppercase font-bold text-rose-400">
                Scheduled Exceptions
              </div>
              <div className="text-2xl font-bold text-rose-400 mt-0.5">1</div>
              <div className="text-[10px] text-rose-300/80">Sync Breach (ASCAP)</div>
            </div>
          </div>
        </div>

        {/* ========================================================================= */}
        {/* SECTION I: UNRESOLVED EXCEPTIONS (WARRANTY EXCLUSIONS) */}
        {/* ========================================================================= */}
        <section className="space-y-4 break-inside-avoid print-break-inside-avoid">
          <div className="flex items-center gap-2 border-b border-rose-800/60 pb-2">
            <AlertOctagon className="h-5 w-5 text-rose-400" />
            <h2 className="text-base font-bold text-white uppercase tracking-wider">
              Section I &mdash; Schedule of Active Unresolved Exceptions (Warranty Exclusions)
            </h2>
          </div>

          <div className="rounded-xl border-2 border-rose-700/60 bg-rose-950/20 p-4 sm:p-5 space-y-4">
            <div className="text-xs text-rose-200/90 leading-relaxed font-serif">
              <strong>STATUTORY NOTICE TO UNDERWRITER:</strong> Pursuant to Policy E&amp;O-2026.1 Section 4(b),
              the items cataloged in this Section I are explicitly excluded from standard Errors &amp; Omissions
              indemnity coverage. Any third-party claim, lawsuit, injunction, or license fee dispute arising from the
              unauthorized exhibition or synchronization of these creative elements remains the sole financial liability
              of the policyholder unless cured or endorsed prior to principal delivery.
            </div>

            {/* Exception Item 12 Card */}
            {exceptionItems.map((exItem) => (
              <div
                key={exItem.stable_lineage_key}
                className="rounded-lg border border-rose-600/40 bg-slate-900/90 p-4 space-y-3 break-inside-avoid print-break-inside-avoid"
              >
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2 border-b border-slate-800 pb-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="rounded bg-rose-950 text-rose-300 border border-rose-700/60 px-2 py-0.5 text-[10px] font-mono font-bold">
                        EXCEPTION #01
                      </span>
                      <h3 className="text-sm font-bold text-white">
                        {exItem.description}
                      </h3>
                    </div>
                    <div className="mt-1 text-xs text-slate-400">
                      Lineage Key: <span className="font-mono text-slate-300">{exItem.stable_lineage_key}</span> &middot;{' '}
                      Scene / Timecode: <span className="text-slate-200">{exItem.scene_or_timecode}</span> &middot;{' '}
                      Asset Type: <span className="font-semibold text-slate-300 uppercase">{exItem.asset_type}</span>
                    </div>
                  </div>

                  <span className="inline-flex rounded bg-rose-950/80 px-2.5 py-1 text-xs font-bold text-rose-300 border border-rose-600/60">
                    EXCLUDED FROM COVERAGE
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                  <div>
                    <span className="block text-[10px] uppercase font-bold text-slate-400">
                      Invalidation Reason &amp; Breach Detail
                    </span>
                    <p className="mt-1 text-slate-200 leading-relaxed">
                      Worldwide exclusive synchronization and master rights assigned in August 2026 to{' '}
                      <strong className="text-rose-300">Vanguard Media Holdings LLC</strong> (administered by Kobalt Music).
                      Prior public domain attestation invalid under European term extension.
                    </p>
                  </div>

                  <div>
                    <span className="block text-[10px] uppercase font-bold text-slate-400">
                      Mandatory Counsel Recommendation
                    </span>
                    <p className="mt-1 text-slate-200 leading-relaxed">
                      {exItem.counsel_action ||
                        'Execute synchronization license with Vanguard Media Holdings prior to final audio mix, or replace cue with pre-cleared production library music.'}
                    </p>
                  </div>
                </div>

                {/* Evidence Citations with Provenance and Hashes */}
                <div className="rounded border border-slate-800 bg-slate-950/70 p-3 text-xs space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-mono font-bold uppercase text-sky-400 flex items-center gap-1.5">
                      <ExternalLink className="h-3.5 w-3.5" />
                      Attributable Registry Evidence (Parallel Search API)
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">
                      Provider Call ID: <code className="text-slate-300">prl_call_993012_music</code>
                    </span>
                  </div>
                  <div className="text-slate-300">
                    <div className="font-semibold text-sky-300 flex items-center gap-2">
                      <a
                        href="https://ascap.com/ace-title-search/midnight-serenade-9921"
                        target="_blank"
                        rel="noreferrer"
                        className="hover:underline text-sky-400 inline-flex items-center gap-1"
                      >
                        ASCAP ACE Repertory &amp; Billboard Rights Bulletin
                        <ExternalLink className="h-3 w-3 inline" />
                      </a>
                      <span className="font-mono text-[10px] text-slate-400">
                        https://ascap.com/ace-title-search/midnight-serenade-9921
                      </span>
                    </div>
                    <p className="mt-1.5 italic font-serif text-slate-300 bg-slate-900/60 p-2 rounded border border-slate-800">
                      &ldquo;Worldwide exclusive synchronization and master rights assigned August 2026 to Vanguard Media Holdings LLC (Administered by Kobalt Music). Prior public domain assertions disputed under European term extension.&rdquo;
                    </p>
                    <div className="mt-1 text-[10px] font-mono text-slate-400">
                      SHA-256 Payload Hash: <code className="text-slate-300">c958448a39a8264582f3a677353f40f098fe5c5b525d8e752989b6574f881028</code>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ========================================================================= */}
        {/* SECTION II: RE-ATTESTED PUBLIC DOMAIN ITEMS */}
        {/* ========================================================================= */}
        {/* ========================================================================= */}
        {/* SECTION II: RE-ATTESTED PUBLIC DOMAIN ITEMS */}
        {/* ========================================================================= */}
        <section className="space-y-4 break-inside-avoid print-break-inside-avoid">
          <div className="flex items-center gap-2 border-b border-sky-700/60 pb-2">
            <CheckCircle2 className="h-5 w-5 text-sky-400" />
            <h2 className="text-base font-bold text-white uppercase tracking-wider">
              Section II &mdash; Re-Attested Public Domain Items (Corroborated Clearance)
            </h2>
          </div>

          <div className="space-y-3">
            {reattestedItems.map((reItem) => (
              <div
                key={reItem.stable_lineage_key}
                className="rounded-xl border border-sky-500/40 bg-sky-950/20 p-4 sm:p-5 space-y-4 break-inside-avoid print-break-inside-avoid"
              >
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2 border-b border-slate-800 pb-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="rounded bg-sky-950 text-sky-300 border border-sky-600/60 px-2 py-0.5 text-[10px] font-mono font-bold">
                        ITEM #11
                      </span>
                      <h3 className="text-sm font-bold text-white">
                        {reItem.description}
                      </h3>
                    </div>
                    <div className="mt-1 text-xs text-slate-400">
                      Lineage Key: <span className="font-mono text-slate-300">{reItem.stable_lineage_key}</span> &middot;{' '}
                      Scene / Timecode: <span className="text-slate-200">{reItem.scene_or_timecode}</span> &middot;{' '}
                      Asset Type: <span className="font-semibold uppercase text-slate-300">{reItem.asset_type}</span>
                    </div>
                  </div>

                  <span className="inline-flex rounded bg-emerald-950/80 px-2.5 py-1 text-xs font-bold text-emerald-300 border border-emerald-600/60">
                    APPROVED (PUBLIC DOMAIN)
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                  <div>
                    <span className="block text-[10px] uppercase font-bold text-slate-400">
                      Creative Delta &amp; Counsel Determination
                    </span>
                    <p className="mt-1 text-slate-200 leading-relaxed">
                      Escalated from 2s out-of-focus background blur to 14s close-up focal dialogue shot.
                      Invalidates prior de minimis clearance; clearance counsel re-attests under United States Public Domain
                      doctrine following verified copyright expiration without statutory renewal.
                    </p>
                  </div>
                  <div>
                    <span className="block text-[10px] uppercase font-bold text-slate-400">
                      Library of Congress Verification Record
                    </span>
                    <p className="mt-1 text-slate-200 leading-relaxed">
                      Registration #B-1946-8821 expired 1974 without timely statutory renewal.
                      Cover artwork is completely free from copyright restriction in the United States.
                    </p>
                  </div>
                </div>

                {/* Evidence Citation with Attributable Provenance */}
                <div className="rounded border border-slate-800 bg-slate-950/70 p-3 text-xs space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-mono font-bold uppercase text-sky-400 flex items-center gap-1.5">
                      <ExternalLink className="h-3.5 w-3.5" />
                      Attributable Source Verification (Library of Congress Records)
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">
                      Provider Call ID: <code className="text-slate-300">prl_call_882910_poster</code>
                    </span>
                  </div>
                  <div className="text-slate-300">
                    <div className="font-semibold text-sky-300 flex items-center gap-2">
                      <a
                        href="https://cocatalog.loc.gov/cgi-bin/Pwebrecon.cgi?v1=1946-crime-detective"
                        target="_blank"
                        rel="noreferrer"
                        className="hover:underline text-sky-400 inline-flex items-center gap-1"
                      >
                        US Copyright Office Historical Catalog - Renewal Records
                        <ExternalLink className="h-3 w-3 inline" />
                      </a>
                      <span className="font-mono text-[10px] text-slate-400">
                        cocatalog.loc.gov/cgi-bin/Pwebrecon.cgi?v1=1946-crime-detective
                      </span>
                    </div>
                    <p className="mt-1.5 italic font-serif text-slate-300 bg-slate-900/60 p-2 rounded border border-slate-800">
                      &ldquo;Registration #B-1946-8821 expired 1974 without timely renewal. Cover artwork in public domain in the United States.&rdquo;
                    </p>
                    <div className="mt-1 text-[10px] font-mono text-slate-400">
                      SHA-256 Payload Hash: <code className="text-slate-300">a1f498bc20379d749be8b0821c4fa92b5e28329623e10d860d5b4e72fb4d0267</code>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ========================================================================= */}
        {/* SECTION III: CERTIFIED CARRIED-FORWARD CLEARANCE REGISTER */}
        {/* ========================================================================= */}
        <section className="space-y-4 break-inside-avoid print-break-inside-avoid">
          <div className="flex items-center gap-2 border-b border-emerald-700/60 pb-2">
            <CheckCircle2 className="h-5 w-5 text-emerald-400" />
            <h2 className="text-base font-bold text-white uppercase tracking-wider">
              Section III &mdash; Certified Carried-Forward Clearance Register (10 Claims &middot; $0.00 Audit Parity)
            </h2>
          </div>

          <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/60">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-950/80 font-mono text-[11px] uppercase text-slate-400">
                  <th className="py-2.5 px-3">#</th>
                  <th className="py-2.5 px-3">Lineage Key</th>
                  <th className="py-2.5 px-3">Scene / TC</th>
                  <th className="py-2.5 px-3">Type</th>
                  <th className="py-2.5 px-3">Description</th>
                  <th className="py-2.5 px-3">v7 Status</th>
                  <th className="py-2.5 px-3">v8 State</th>
                  <th className="py-2.5 px-3 text-right">Audit Cost</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                {carriedItems.map((cItem, index) => (
                  <tr key={cItem.stable_lineage_key} className="hover:bg-slate-800/30">
                    <td className="py-2.5 px-3 font-mono font-bold text-slate-500">
                      {String(index + 1).padStart(2, '0')}
                    </td>
                    <td className="py-2.5 px-3 font-mono font-medium text-slate-300">
                      {cItem.stable_lineage_key}
                    </td>
                    <td className="py-2.5 px-3 text-slate-300 whitespace-nowrap">
                      {cItem.scene_or_timecode}
                    </td>
                    <td className="py-2.5 px-3">
                      <span className="rounded bg-slate-800 px-1.5 py-0.5 text-[10px] font-mono text-slate-300 uppercase">
                        {cItem.asset_type}
                      </span>
                    </td>
                    <td className="py-2.5 px-3 text-slate-300 max-w-xs truncate">
                      {cItem.description}
                    </td>
                    <td className="py-2.5 px-3 font-semibold text-slate-300">
                      APPROVED
                    </td>
                    <td className="py-2.5 px-3">
                      <span className="inline-flex rounded px-1.5 py-0.5 text-[10px] font-semibold badge-carried">
                        CARRIED FORWARD
                      </span>
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono text-emerald-400 font-semibold">
                      $0.00
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* ========================================================================= */}
        {/* SECTION IV: LEGAL COUNSEL ATTESTATION & UNDERWRITER CERTIFICATION */}
        {/* ========================================================================= */}
        <section className="border-t-2 border-slate-700 pt-6 space-y-6 break-inside-avoid print-break-inside-avoid">
          <div>
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
              <Scale className="h-4 w-4 text-sky-400" />
              Section IV &mdash; Legal Counsel Attestation &amp; Underwriter Certification
            </h2>
            <p className="mt-2 text-xs text-slate-300 font-serif leading-relaxed">
              I, <strong>Sarah Jenkins, Esq.</strong>, Lead Clearance Counsel for Blockbuster Cinema LLC,
              hereby warrant and certify under penalty of insurance policy cancellation that: (1) All twelve (12)
              rights-bearing creative uses identified in Production Revision v8 have been reviewed against the
              Version 7 locked baseline; (2) Ten (10) creative uses possess identical context and prominence and are
              certified carried forward without additional clearance audit expense; (3) Item 11 has been re-attested
              based on corroborating Library of Congress public domain renewal lapse records; (4) Item 12 has been
              formally designated as an open Unresolved Exception for explicit underwriter exclusion.
            </p>
          </div>

          {/* Signature Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-4 break-inside-avoid print-break-inside-avoid">
            {/* Counsel Signature Block */}
            <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4 space-y-3 break-inside-avoid print-break-inside-avoid">
              <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                Clearance Counsel of Record
              </div>
              <div className="border-b border-slate-700 pb-2 pt-4">
                <span className="font-serif italic text-lg text-sky-300 font-semibold">
                  Sarah Jenkins, Esq.
                </span>
              </div>
              <div className="text-xs space-y-0.5 text-slate-400">
                <div className="font-medium text-slate-300">
                  Lead Production Clearance Counsel, Lienmark Legal Partners LLP [FICTIONAL / DEMO COUNSEL]
                </div>
                <div>State Bar of California &middot; License #284910</div>
                <div>Entertainment Clearance &amp; Risk Practice Group</div>
                <div className="font-mono text-[10px] text-slate-400 mt-1">
                  Digital Attestation Timestamp: {formattedDate} (UTC Certified)
                </div>
              </div>
            </div>

            {/* Carrier Underwriter Binder Block */}
            <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/40 p-4 space-y-3 break-inside-avoid print-break-inside-avoid">
              <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                Underwriter Acknowledgment (Pending Review)
              </div>
              <div className="border-b border-dashed border-slate-600 pb-2 pt-6 text-center text-xs text-slate-500 font-mono">
                ____________________________________________________
              </div>
              <div className="text-xs space-y-0.5 text-slate-400 text-center">
                <div className="text-slate-300 font-medium">Authorized Carrier / Syndicate Underwriter Signature</div>
                <div>Lloyd&apos;s Syndicate 1888 &amp; Hartford Syndicate Group</div>
                <div className="text-amber-400 font-semibold text-[11px] mt-1">
                  &bull; STATUS: PENDING UNDERWRITER REVIEW &mdash; NO COVERAGE BOUND
                </div>
              </div>
            </div>
          </div>

          {/* Document Security Digest */}
          <div className="rounded-lg bg-slate-950 p-3 text-center text-[10px] font-mono text-slate-400 border border-slate-900">
            CRYPTOGRAPHIC AUDIT SEAL: SHA256:7f3a9b1c2d4e80f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9
            &middot; LIENMARK FAIL-CLOSED WARRANTY RECONCILED
          </div>
        </section>

        {/* PROMINENT STATUTORY UNDERWRITING DISCLAIMER BANNER (FOOTER) */}
        <div className="rounded-xl border border-rose-600/50 bg-rose-950/30 p-4 text-xs text-rose-200 leading-relaxed font-sans shadow-inner">
          <strong className="font-bold text-rose-300">LEGAL &amp; UNDERWRITING DISCLAIMER:</strong> THIS ARTIFACT IS A VERSION-BOUND SCHEDULE OF UNRESOLVED CLEARANCE EXCEPTIONS FOR DEMONSTRATION AND INFORMATIONAL PURPOSES ONLY. NO ARTIFACT GENERATED BY LIENMARK CONSTITUTES OR CLAIMS FORMAL UNDERWRITING APPROVAL, POLICY BINDING, INSURANCE COVERAGE, LEGAL OPINION, OR LEGAL CERTAINTY. COVERAGE IS SUBJECT EXCLUSIVELY TO A SEPARATELY EXECUTED POLICY BINDER WITH AN ADMITTED OR SURPLUS LINES CARRIER.
        </div>
      </div>
    </div>
  );
}
